-- Auto-generated by patchupdate.lua
return {
	base = 0x17A44C0,


	-- Player info
	playerName = 0x1711EF4,
	playerAccount = 0x1712020,

	playerDir1 = 0x17A4430,
	playerDir2 = 0x17A4434,
	playerX = 0x17A4448,
	playerZ = 0x17A444C,
	playerY = 0x17A4450,

	playerbasehp = 0x1715B70,
	playerHPoffset = {0x168, 0x8},
	playerMaxHPoffset = {0x168, 0xC},
	playerKarmaoffset = {0x1B0, 0x4, 0x1B4},
	playerGoldoffset = {0x4, 0x16C, 0x50},
	playerInCombat = 0x16C903C,
	playerDowned = 0x171549C,

	skillCDaddress = 0x16EBE78,
	statbase = 0x16EBE78,
	actlvlOffset = 0x84,
	adjlvlOffset = 0xAC,
	TargetMob = 0x17EB100,
	TargetAll = 0x17EB118,

	XPbase = 0x17EA7EC,
	xpOffset = {0x80, 0x120, 0x14, 0x4},
	xpnextlvlOffset = {0x80, 0x120, 0x14, 0xC},


	-- Target info
	targetbaseAddress = 0x171E278,
	targetXoffset = {0x8, 0x2C, 0x104},
	targetZoffset = {0x8, 0x2C, 0x108},
	targetYoffset = {0x8, 0x2C, 0x10C},


	-- Interaction (F key) stuff
	Finteraction = 0x17EB0E8,
	FtextAddress = 0x1711DCC,
	FtextOffset = {0x0, 0x94, 0x14, 0x22},


	-- Input, movement, etc.
	moveForward = 0x17ED990,
	moveBackward = 0x17ED994,
	turnLeft = 0x17ED9A0,
	turnRight = 0x17ED9A4,


	-- UI based stuff
	mousewinX = 0x17EB124,
	mousewinZ = 0x17EB128,
	mousepointX = 0x17EB144,
	mousepointZ = 0x17EB148,
	mousepointY = 0x17EB14C,

	loadingbase = 0x171339C,
	loadingOffset = {0xC8, 0x4, 0x0, 0x3BC},
	
	objectArray = 0x17EB188,

	--[[ NOTE: Unorganized addresses
		Anything below this line has (probably) *NOT* been updated automatically!
		It has only been retained from previous versions.
	--]]
	playerbaseui = 0x17EB088,
	playerVisZ = {0x44, 0x1C, 0x5C, 0xB8},
	playerVisX = {0x44, 0x1C, 0x5C, 0xB4},
	speed = 0x17EB190,
	playerServY = {0x44, 0x1C, 0x88, 0xD8},
	FidOffset = {0x0, 0x94, 0x14, 0x8},
	playerServZ = {0x44, 0x1C, 0x88, 0xD4},
	playerServX = {0x44, 0x1C, 0x88, 0xD0},
	speedOffset = {0x44, 0x1C, 0x170},
	playerVisY = {0x44, 0x1C, 0x5C, 0xBC},
}
