-- Auto-generated by update.lua
addresses = {
	playercoords = 0x162F1FC,
	playerDir1 = 0x1C,
	playerDir2 = 0x20,
	playerX = 0x28,
	playerZ = 0x2C,
	playerY = 0x30,

	playerbasehp = 0x15A5870, 
	playerHPoffset = {0x150,0x3C,0x10},
	playerMaxHPoffset = {0x150,0x3C,0x14},
	playerInCombat = 0x15A4698,
	Finteraction = 0x1675180,
	lootwindow = 0x167431C,
	TargetMob = 0x1675198,
	TargetAll = 0x16751A4,
	Targetunk = 0x16751B0,
}
