-- Auto-generated by update.lua
addresses = {
	playerName = 0x15AD428,
	playerAccount = 0x15AD4F8,
	loadingbase = 0x15AE8D0,
	loadingOffset = {0xC8, 0x4, 0x0, 0x3BC},

	playerDir1 = 0x163B7AC,
	playerDir2 = 0x163B7B0,
	playerX = 0x163B7C4,
	playerZ = 0x163B7C8,
	playerY = 0x163B7CC,

	playerbasehp = 0x15B1A3C,
	playerHPoffset = {0x150,0x3C,0x10},
	playerMaxHPoffset = {0x150,0x3C,0x14},
	playerKarmaoffset = {0x1B0, 0x4, 0x1B4},
	playerGoldoffset = {0x154, 0x50},
	playerInCombat = 0x15B1890,
	playerDowned = 0x15B137C,

	Finteraction = 0x1681720,
	TargetMob = 0x1681738,
	TargetAll = 0x1681750,
	mousewinX = 0x1681758,
	mousewinZ = 0x168175C,
	mousepointX = 0x1681778,
	mousepointZ = 0x168177C,
	mousepointY = 0x1681780,

	targetbaseAddress = 0x1682EDC,
	targetXoffset = {0x30, 0x5C, 0x110},
	targetZoffset = {0x30, 0x5C, 0x114},
	targetYoffset = {0x30, 0x5C, 0x118},

	moveForward = 0x1682FA8,
	moveBackward = 0x1682FAC,
	turnLeft = 0x1682FB8,
	turnRight = 0x1682FBC,

	FtextAddress = 0x1683084,
	FtextOffset = {0x0, 0xC4, 0x22},

}
